name: lychakingo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3 
  cloud_firestore: ^5.6.7
  http: ^1.3.0
  cloud_functions: ^5.5.0
  intl: ^0.20.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/backgrounds/